### ISSUE TITLE
Bug? Mabye!

### ISSUE THREAD

**Issue by Cosido** [ustc-zzzz/VirtualChest#101]
I recently Updated my servers from F2809/SF3616 to the latest of both (F2838/SF3784)
Lastest VC as well, rc-5

I can use it fine, nothing seems to be broken or not functioning. 
However when using any vchest inventory, I get this spammed in console
https://pastebin.com/CENvYUhs

**Comment by ustc-zzzz** [comment]
It seems that your configuration on `Slot16` is incorrect. Please check the configuration there.
