### ISSUE TITLE
Could not pass  FMLPostInitializationEvent 

### ISSUE THREAD

**Issue by Trnrr** [ustc-zzzz/VirtualChest#104]
This error shows on server start. This is a fresh plugin install and there are only the default configs atm.
https://gist.githubusercontent.com/Trnrr/9279cf14717e931ddabecc35b5c37192/raw/f9329a99978f846ec6841c55cef03b48e2defc8a/VC%2520error

Placeholderapi 4.5.1
VirtualChest-1.0.0-rc-5
spongeforge-1.12.2-2838-7.1.7-RC3878

**Comment by ustc-zzzz** [comment]
Closed since it is said that the issue is caused by PlaceholderAPI plugin.

**Comment by Trnrr** [comment]
Apologies , I forgot about this. I fixed it by using this version of PlaceholderAPI https://github.com/randombyte-developer/PlaceholderAPI/releases/ instead of rojos

**Comment by drassasmc** [comment]
It's not working for me... and I tested with both PlaceholderAPI(rojo and randombyte) with lot of versions of VirtualChest(from -rc2 to latest)... obviously without duplicating plugins

I'm currently using(doesn't work):
Placeholderapi 4.5.1 (randombyte)
VirtualChest-1.0.0-rc-5
spongeforge-1.12.2-2838-7.1.7-RC3903

**Comment by drassasmc** [comment]
I tried to "downgrade" the spongeforge version and it's work now

I'm currently using:
Placeholderapi 4.5.1 (randombyte)
VirtualChest-1.0.0 (latest release)
spongeforge-1.12.2-2838-7.1.7-RC3878

**Comment by Trnrr** [comment]
@drassasmc does it show the same error I reported or a different one? If its a different one make a new ticket. If its the same then zzzz can re open this whenever he sees it.

**Comment by drassasmc** [comment]
It's exactly the same error, I tested with multiple combinations of PAPI with VChest with latest sponge(2838-7.1.7-RC3903) and I got everytime the same error.
When I change my sponge to an old version it's work fine.
