### ISSUE TITLE
Add a cost to clicking an item

### ISSUE THREAD

**Issue by Jaskirat-Boparai** [ustc-zzzz/VirtualChest#11]
Hello,

I was wondering if you could make it so a player can charged a certain amount of currency to click an icon in configuration, so for example:

`currency_type = tokens`
`amount_to_charge = 10`

In the above example, the currency is tokens and the cost of clicking an icon and running the primary/secondary action in the gui is 10 tokens. If they do not have 10 or more tokens, it doesn't run the primary/secondary action, but if they do have 10 or more tokens, it runs successfully.

Would it then be possible to add an API where people can create currency that will work as a virtual chest currency? The reason for this is because we have a custom plugin that creates tokens which can be given to players so that they can purchase items, and we would look to hook it into this api so we can use virtual chests and the custom plugin in conjunction.

Thanks!

**Comment by ustc-zzzz** [comment]
Well, I have been busy with my dissertation for bachelor’s degree for several days, and It is available in v0.3.6 now.
In fact, My original plan is to introduce this feature in v0.4.0, while a lot of plugin users such as you want it to be added as soon as possible, so I changed my plan.
