### ISSUE TITLE
Not working with placeholder4.5.1

### ISSUE THREAD

**Issue by yoshino-lin** [ustc-zzzz/VirtualChest#114]
如题...望修复...

**Comment by hellbringer616** [comment]
I'm afraid i do not know what your question is..
But! i do know that the Official Placeholder API 4.5.1 is broken.
use this file instead.

这是由Google翻译翻译的。

官方占位符API 4.5.1已损坏。
请改用此文件。

https://github.com/randombyte-developer/PlaceholderAPI/releases

**Comment by yoshino-lin** [comment]
> I'm afraid i do not know what your question is..
> But! i do know that the Official Placeholder API 4.5.1 is broken.
> use this file instead.
> 
> 这是由Google翻译翻译的。
> 
> 官方占位符API 4.5.1已损坏。
> 请改用此文件。
> 
> https://github.com/randombyte-developer/PlaceholderAPI/releases

Yes, I am asking about placeholder... Have no idea what is going on... But thank you so much!

**Comment by hellbringer616** [comment]
@yoshino-lin can you confirm if the above fixed the issue?
If so please close this comment.
