### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by randombyte-developer** [ustc-zzzz/VirtualChest#12]
Hi!

Could provide an example how to set a `GameProfile` to a skull? The Keys is `REPRESENTED_PLAYER`. How are the key and the `DataSerializable` serialized to the config.
To make these things easier a command to generate those data would be very useful, like it outputs the serialized item data of the item you are holding in your hand.

**Comment by ustc-zzzz** [comment]
Well, maybe Sponge missed something. I could not find the deserializer of `GameProfile`.
May be you can use `UnsafeData` instead, by which you cound set the NBT of the item like this:
        Item {
            ItemType = "minecraft:skull"
            Count = 1
            UnsafeDamage = 3
            UnsafeData = {
                SkullOwner = "Dinnerbone"
            }
        }
