### ISSUE TITLE
SkullOwner variable

### ISSUE THREAD

**Issue by lightningo7** [ustc-zzzz/VirtualChest#13]
I've been trying to create an item that will show the users skull using PlaceHolderAPI and it is not working. Am I doing something wrong or is this an issue?

    Position-1-1 = {
        Item {
            Count = 1
            ItemType = "minecraft:skull"
            UnsafeDamage = 3
            UnsafeData = {
                SkullOwner = "%player%"
            }
            DisplayName = "&1Serf"
            ItemLore = [
                "&eYou are currently this rank."
            ]
        }

**Comment by ustc-zzzz** [comment]
Fixed in v0.3.8.
