### ISSUE TITLE
Feature Request: Required Item

### ISSUE THREAD

**Issue by lightningo7** [ustc-zzzz/VirtualChest#15]
It would be nice if there was a "Required Item" feature where it would take the "Required Item" if there was one set.

**Comment by Telmudjin** [comment]
I agree !

**Comment by ustc-zzzz** [comment]
Please try v0.3.8.
<https://github.com/ustc-zzzz/VirtualChest/blob/v0.3.8/resources/assets/virtualchest/examples/example.conf#L216>
