### ISSUE TITLE
Could not pass FMLServerStartedEvent to Plugin

### ISSUE THREAD

**Issue by EmanYm** [ustc-zzzz/VirtualChest#16]
During early server loading I see this:
>[17:13:52] [Server thread/INFO] [virtualchest]: Start loading config ...
[17:13:52] [Server thread/INFO] [virtualchest]: Loading config complete.

Then at the [I get this](https://hastebin.com/exuzovoqug.md).

All of the commands seem to work as expected from the console.

================================================================

>/sponge version
[17:29:47] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-c675e80
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2433
    Minecraft Forge: 12.18.3.2316

>/vc version
================================================================
[17:27:47] [Server thread/INFO]: VirtualChest v0.3.7
================================================================
[17:27:47] [Server thread/INFO]: Released at 07 Jun 2017
[17:27:47] [Server thread/INFO]: Git commit hash: 09de318
================================================================

**Comment by ustc-zzzz** [comment]
Well, which economy plugin do you use in your server?

**Comment by EmanYm** [comment]
TotalEconomy 1.7.0-dev2

**Comment by ustc-zzzz** [comment]
Well, maybe you did not specify which currency is the default one in the configuration file of TotalEconomy. I'm now working on this problem, you can specify a default one before I fix it XD

**Comment by ustc-zzzz** [comment]
Try v0.3.8 now.
