### ISSUE TITLE
Cost items

### ISSUE THREAD

**Issue by PixelmonPRO** [ustc-zzzz/VirtualChest#17]
Hello! I have an idea, add cost items.
Example: 
`PrimaryAction = "cost: minecraft:diamond 10; console: say %player_name% has found the magic power of the compass!"`
And player open next menu / commands and other)

**Comment by ustc-zzzz** [comment]
Please try the new `cost-item` action in v0.3.8.
<https://github.com/ustc-zzzz/VirtualChest/blob/v0.3.8/resources/assets/virtualchest/examples/example.conf#L216>

**Comment by KhaozFrost** [comment]
PlaceholderAPI-4.2.jar
VirtualChest-0.4.2.jar
spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar

Took a look at this using the example.conf the wheat product; you can buy it but once its in your hand it wont sell. Reasons why using 4.2 VC over 4.3 \\ 4.2 allows the balance requirements but 4.3 doesnt so i will not update to latest on it.
