### ISSUE TITLE
Cost-item not work(

### ISSUE THREAD

**Issue by PixelmonPRO** [ustc-zzzz/VirtualChest#18]
Hello! I try add cost-item.
I try `example.conf`, and have next:
<img width="1109" alt="screenshot at 05 02-50-43" src="https://user-images.githubusercontent.com/26658563/30040239-3249dce2-91e5-11e7-832c-cf03c2860874.png">

**Comment by ustc-zzzz** [comment]
Could you please provide your configuration file? I consider that there are some format errors in your configuration.

**Comment by PixelmonPRO** [comment]
I tried to customize my own, it did not work out.
I tried from the examples this: https://github.com/ustc-zzzz/VirtualChest/blob/master/resources/assets/virtualchest/examples/example.conf
The screenshots above are from him :)

**Comment by ustc-zzzz** [comment]
It works normally on my computer. Please tell me more about your server such as the version of Sponge, MinecraftForge, and Minecraft.
You can extract the example files by command `/vc reload extract-examples`. Make sure that those two files (`example.conf` and `example2.conf`) have not already been there.
