### ISSUE TITLE
PlaceholderAPI Breaks Virtual Chest

### ISSUE THREAD

**Issue by xxsuperdreamxx** [ustc-zzzz/VirtualChest#19]
SpongeAPI version: [spongevanilla-1.10.2-5.2.0-BETA-393](https://www.spongepowered.org/downloads/spongevanilla/stable/1.10.2 )

PlaceholderAPI version: [PlaceholderAPI v4.1](https://ore.spongepowered.org/rojo8399/PlaceholderAPI/versions/4.1)

VirtualChest version: [Virtual Chest 0.3.8](https://ore.spongepowered.org/zzzz/VirtualChest/versions/0.3.8)

Error log [if any]: (https://pastebin.com/vLwsuwi6)

Description: Virtual Chest is using PlaceholderAPI and if you don't use it and open the Menu it doesn't show the name and other placeholders but when I try to open the Menu with PlaceholderAPI it doesn't work. Tried the 1.11.2 and 1.12 versions still doesn't work I remove Nucleus and Nucleus Gluon to see if that breaks the plugins but still doesn't work

**Comment by ustc-zzzz** [comment]
Well, PlaceholderAPI 4.x breaks the backward compatibility and plugins which depends on Placeholder 3.x needs to do something more for the compatibility with the new api. VirtualChest is now working on this. Please wait for the v0.3.9 release or downgrade the PlaceholderAPI to 3.x for the urgent needs.
