### ISSUE TITLE
Command Variable

### ISSUE THREAD

**Issue by Rubbertjuh** [ustc-zzzz/VirtualChest#2]
First of all, great work on the plugin.
Really enjoying is so far! 
I'm trying to execute a command 
        PrimaryAction = "effect %player% 21"

Could you possible add in a player variable? This way we can add in more commands that require a username to function?

**Comment by Jaskirat-Boparai** [comment]
The place holder you provide in your example config files, the {player} also doesn't work with action events, also seems to work in the item lore. Otherwise great plugin.

**Comment by ustc-zzzz** [comment]
Oh it's my fault. You can try the new version (v0.2.3) now:
<https://github.com/ustc-zzzz/VirtualChest/releases/tag/v0.2.3>
