### ISSUE TITLE
Problem with %player_name%

### ISSUE THREAD

**Issue by Gohu29** [ustc-zzzz/VirtualChest#21]
When I test your example with the wheat, console do this command

> 27.09 21:37:56 [Server] Server thread/INFO [nucleus]: Server ran the command: /give %player_name% minecraft:wheat 9

VirtualChest v0.3.9
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-c675e80
SpongeForge: 1.10.2-2281-5.2.0-BETA-2610
Minecraft Forge: 12.18.3.2488

**Comment by ustc-zzzz** [comment]
Make sure that your server has installed the PlaceholderAPI plugin.

**Comment by Gohu29** [comment]
That's work sorry for this issue.
Thank you for the help and the plugin.
