### ISSUE TITLE
API 7.0.0 not working

### ISSUE THREAD

**Issue by OttoOttoman** [ustc-zzzz/VirtualChest#22]
So I updated from 1.10.2 to 1.12.2 Yay. But when used /vc open the GUI pops up but nothing inside would work... meaning by the items with lores and names were there but could take them out and put it in my inventory and the click then command activates or switch GUI doesn't happen.

**Comment by ustc-zzzz** [comment]
VC does not support api v7.0.0 now (v0.3.9). Please refer to #20.

**Comment by ustc-zzzz** [comment]
SpongeForge has been updated 19 hours ago, and 1.12.x is now supported by VirtualChest.
