### ISSUE TITLE
Version 0.4.0 - problem with new configs

### ISSUE THREAD

**Issue by Krosta8** [ustc-zzzz/VirtualChest#23]
Hello,
Nice to see the new version, but unfortunatelly, I cantt get it work. I tried to delete the whole config folder and its generated a new one. On the server I can’t open any of the default examples. It just says "The specified chest GUI (example) is not found.

Do you know, why is this happening?
Sponge 1.10.2, API 5.2.0. Everything load correctly.

I posted it on Sponge Ore too, but I would like to have quick response, so I tried to wrote it here too 😄

**Comment by ustc-zzzz** [comment]
Please check if you have the corresponding permissions: `virtualchest.open.self.example`, and `virtualchest.open.self.example2`

**Comment by Krosta8** [comment]
I have all permissions (*) and using LuckPerms

**Comment by ustc-zzzz** [comment]
Oh, I got it. It's a stupid mistake. VC v0.4.1 will be released soon.

**Comment by ustc-zzzz** [comment]
OK, try v0.4.1 now.

**Comment by Krosta8** [comment]
Thank you very much, it is working now! 😃
