### ISSUE TITLE
VirtualChest and Sponge API 7.0.0

### ISSUE THREAD

**Issue by Krosta8** [ustc-zzzz/VirtualChest#24]
Hello,
I know, that your plugin does not currently support Sponge API 7.0.0, but I just want to let you know, that it is "working", just the inventory is empty. You can see it on this picture: 
![image](https://user-images.githubusercontent.com/30801575/31905890-da351ba4-b82f-11e7-9b31-40051fcd1a32.png)

Do you think, that you can make a working version for Sponge API 7.0.0 to the end of this month?
I really want to use your plugin on my future server, which will be on Sponge API 7.0.0.

Thank you a lot,
Krosta8

**Comment by ustc-zzzz** [comment]
SpongeForge has been updated 19 hours ago, and 1.12.x is now supported by VirtualChest.
