### ISSUE TITLE
Add animations slots :)

### ISSUE THREAD

**Issue by PixelmonPRO** [ustc-zzzz/VirtualChest#25]
Hello! Plugin `GWM-Crates` have very fun animations in slots, example:
![kzthsqs](https://user-images.githubusercontent.com/26658563/32077338-c430ab60-baab-11e7-9d7b-d09caa44283f.gif)
I would like you to add this feature to your wonderful plugin :) Many use it to create a menu that would very nicely embellish it)

**Comment by ustc-zzzz** [comment]
It is available in VC 0.4.x, and examples are on Slot0 and Slot8 of [`example2.conf`](https://github.com/ustc-zzzz/VirtualChest/blob/v0.4.1/resources/assets/virtualchest/examples/example2.conf).
For example, if you want to use 16 colorful glass panes and want them to be changed 10 times per second (2 gameticks), you can do it like this:
```hocon
  Slot0 = [{
    Item {
      Count = 1
      ItemType = "minecraft:stained_glass_pane"
      UnsafeDamage = 0
    }
    Requirements = "tick % 32 < 2"
  }, {
    Item {
      Count = 1
      ItemType = "minecraft:stained_glass_pane"
      UnsafeDamage = 1
    }
    Requirements = "tick % 32 < 4"
  } # etc.
  , {
    Item {
      Count = 1
      ItemType = "minecraft:stained_glass_pane"
      UnsafeDamage = 15
    }
    Requirements = "tick % 32 < 32"
  }]
```
As is already shown in the [wiki](https://github.com/ustc-zzzz/VirtualChest/wiki/3-Slots-And-Requirements#javascript), the variable `tick` is ticks from opening the inventory, the initial value of which is set to `0` when you open the inventory.
At that moment, the first item meet the requirements (`tick % 32 => 0 % 32 => 0`, and `0 < 2`) and will be shown in the inventory.
When 2 gameticks passed, the variable `tick` changes to `2` and `2 < 2` is `false` now, then VirtualChest will try the second item. Obviously, `2 < 4`, and the second item will be shown.
And so on until the 16nd item is shown in the inventory. At that time, `tick` is `30`.
Then two gameticks passed and `tick` is `32` now, `32 % 32 => 0`, then it returns to the first item.

You should also set the [`UpdateIntervalTick`](https://github.com/ustc-zzzz/VirtualChest/blob/v0.4.1/resources/assets/virtualchest/examples/example2.conf#L63) option to the value which you want to set for the interval of two updates. In this example, it should be `2`, and VirtualChest will update the inventory every two gameticks. If it is set to 0, VirtualChest will not update the inventory except the first time.

If you still have some thing you do not understand, feel free to ask me in this issue. So sorry for my poor English =_=
