### ISSUE TITLE
Multi-Currency "cost:" support?

### ISSUE THREAD

**Issue by Krosta8** [ustc-zzzz/VirtualChest#26]
Hello,
I have a question about multi-currency and cost command.

Is there an option how to perform the transaction from first currency or second currency?

Now, it is taking the default currency, but is there an option how to perfrom transaction from second currency? 
I know, that I can still use classic command for pay method from the plugin, but I would like to do it directly from the VC, is it possible?

Thank you a lot!

**Comment by ustc-zzzz** [comment]
It is possible to do so in theory like this: `cost: totaleconomy:dollar:7;`
I have not ever tested this case before, so please tell me if it is available after you tried this, and I'll write it to the wiki if it is.

**Comment by Krosta8** [comment]
It works exactly like you wrote! Thank you.

By the way, the same logic is working for Requirements.

**Comment by ustc-zzzz** [comment]
It should be `%economy_balance_totaleconomy:dollar% >= 50`.
Please refer to the wiki: [Slots And Requirements](https://github.com/ustc-zzzz/VirtualChest/wiki/3-Slots-And-Requirements#frequently-used-requirement-string-patterns)

**Comment by Krosta8** [comment]
I tried this, but it won't work. I have to wait for new update of PlaceHolderAPI, because the mistake must be on its side.
Thank you again.
