### ISSUE TITLE
Ignored permissions and spam in a console

### ISSUE THREAD

**Issue by Krosta8** [ustc-zzzz/VirtualChest#29]
Hello,
I'm runnig the newest version of VirtualChest (4.1) and I tried to use ignored permissions, but I can't open the GUI.  On the version below 4.0 it works.

Not even given example is working. When I give myself all permission, I still can't open the next GUI (where is ignored permission set).
I tried to give myself vchest.open.* and again, can't open GUI with ignored permision set.

I just want to set, that the player can open shop directly, but everything else only through the GUI (on clicked item) and can't open them directly.
Example:
/vchest open shop
and in shop is another items, which will open for example: "ae2" and I won't to let them open it directly through /vchest open ae2 command.
Is it still possible to do this via ignored permissions?

Another problem, which I found (maybe just bad configuration?), is with spam in a console.
When I open a GUI, virtualchest is keep spamming to the console this:

> [17:14:56] [Server thread/DEBUG] [virtualchest]: Execute script for player EntityPlayerMP['Krosta8'/383, l='DIM1', x=3.50, y=63.00, z=17.50]
[17:14:56] [Server thread/DEBUG] [virtualchest]: Literal: 
[17:14:56] [Server thread/DEBUG] [virtualchest]: Result: true

This one is spamming a lot.
Sometimes it shows up this:

> [17:14:56] [Server thread/DEBUG] [virtualchest]: Execute script for player EntityPlayerMP['Krosta8'/383, l='DIM1', x=3.50, y=63.00, z=17.50]
[17:14:56] [Server thread/DEBUG] [virtualchest]: Literal: %economy_balance% >= 7

But it's okay, just one time or two times per open GUI.

The biggest problem is, that sometimes is getting bugged. Nobody is on the server and it spams the same line more than 15x per second (maybe for every tick?). In a hour the log has more than 10GB and the server shut down, because there is not enough space.

Any solution for this? 

Thank you a lot.

**Comment by ustc-zzzz** [comment]
1. Sponge does not support wildcard charactors such as `*` or `?`, but Sponge's permission system has relations in difference permission strings ("inheritance" system). `vchest.open.self.example` "inherit"s `vchest.open.self`, so if a player has `vchest.open.self` permission, he or she can open all the menus for himself. So `vchest.open` can be used instead.

2. They are just debug messages, and should not have been sent to the console. Maybe you are reading log files?

**Comment by Krosta8** [comment]
1. I tried `vchest.open`, but it didn't work, so I tried `virtualchest.open` and it works.
2. It is in the `fml-junk-earlystrartup.log`, but sometimes it is getting bugged and it spams all the time (as I can later see in this log) and it caused the size 10GB of the log within an hour. Is there a way, how to disable this debug messages?
