### ISSUE TITLE
资词资词~

### ISSUE THREAD

**Issue by subtank** [ustc-zzzz/VirtualChest#3]
很不错的插件~
不过还没实装到我的服务器整合包中
关于经济插件，能做出来一个类似商店的东西嘛。如果可以的话，我可以加到空岛生存里面咯~

**Comment by ustc-zzzz** [comment]
现在（v0.3.6）能做出来了→_→

**Comment by subtank** [comment]
好的，我去看下新版本的~好久没关注mc了
