### ISSUE TITLE
Forking help

### ISSUE THREAD

**Issue by randombyte-developer** [ustc-zzzz/VirtualChest#31]
Hi!

I am planning to fork this project to integrate it tighter with other private plugins. I would like to change the `ItemStack`s that are displayed in the inventory. These should be replaced completely in some cases.
So could you point me to the code piece that generates the ItemStack(Snapshot) for the inventory?

RandomByte

**Comment by ustc-zzzz** [comment]
VirtualChest always updates every slot in the inventory, so I just iterate all the slots in the inventory ([VirtualChestInventory.java](https://github.com/ustc-zzzz/VirtualChest/blob/master/src/com/github/ustc_zzzz/virtualchest/inventory/VirtualChestInventory.java#L98-L114)) and update the slot in order ([VirtualChestItem.java](https://github.com/ustc-zzzz/VirtualChest/blob/master/src/com/github/ustc_zzzz/virtualchest/inventory/item/VirtualChestItem.java#L113)).
I remember that Sponge provided a way to set the item in a specific slot directly. SpongeAPI provides a method called `query` and you can pass an `InventoryProperty` such as `SlotIndex` in it. However, I've not ever tried this way so I don't know if Sponge has implemented it correctly.

**Comment by randombyte-developer** [comment]
Thanks! That's exactly what I was looking for. Your code seems to be well written.
I'll leave this issue open in case I have more questions.

**Comment by ustc-zzzz** [comment]
3 days has passed and I consider that reopening this issue again if you have some new questions is a better choice.

**Comment by randombyte-developer** [comment]
Yeah, sorry.
