### ISSUE TITLE
3.9 to 4.0

### ISSUE THREAD

**Issue by MageFX** [ustc-zzzz/VirtualChest#32]
Hi, 

Would it be possible to create a 3.9 to 4.0/4.1 config conversion tool. I've created a GUI which contains over 1400 files. I am currently tweaking this package and will be releasing it on the 3.9 VC but would like to release the GUI package on 4.1 also. I was hoping to Batch edit my files but I'm not sure if this is possible.

Thank you.
MageFX

**Comment by ustc-zzzz** [comment]
Currently available data shows that there are less than 10% of the servers still using v0.3.x, so I will no longer consider v0.3.x's support.
