### ISSUE TITLE
Cost Requirements broken now..?

### ISSUE THREAD

**Issue by KhaozFrost** [ustc-zzzz/VirtualChest#35]
Slot10 {
        Item {
            Count = 1
            ItemType = "pixelmon:pixelmon_sprite"
            UnsafeDamage = 0
            DisplayName = "&d&lSlot 1"
            ItemLore = []
        UnsafeData {
            SpriteName = "pixelmon:sprites/eggs/egg1"
        }
        }
        KeepOpen = false
        PrimaryAction {
            Command = "cost: 1000; delay: 15; console: lp user %player_name% permission settemp pixelupgrade.command.checkegg true 10s; delay: 5; eggcheck 1 -c"
            KeepInventoryOpen = true
        }
        SecondaryAction {
            Command = "cost: 1000; delay: 15; console: lp user %player_name% permission settemp pixelupgrade.command.checkegg true 10s; delay: 5; eggcheck 1 -c"
            KeepInventoryOpen = true
        }
        IgnoredPermissions = [
            "pixelupgrade.commands.checkegg"
        ]
        Requirements = "%economy_balance% >= 10"
    },

The requirement doesn't detect balance. I can remove it shows up but otherwise it doesnt. with my balance at 100,000+

even things like 
    Slot0 = [{
        Item {
            Count = 1
            ItemType = "minecraft:wheat"
            UnsafeDamage = 0
        }
        Requirements = "%economy_balance% >= 10"
    },
dont show up in the menu; why isn't it detecting the eco balance now? worked in 3.9...

**Comment by KhaozFrost** [comment]
going to assume this is why its not detecting the balance http://prntscr.com/hcopgr running Placeholderapi 4.2

**Comment by Krosta8** [comment]
I have the same issue like you. After some server restarts, config is being reseted to default, where is economy disabled. I already post it on PlaceHolderAPI github. You can confirm, that it is not only my problém :smile:

**Comment by KhaozFrost** [comment]
need this fixed asap.... cant do anything with my menus now that this is broken.

**Comment by ustc-zzzz** [comment]
I did some tests. The PlaceholderAPI v4.2 cannot parse the token `%economy_balance%` to the real value of the player's balance, and PlaceholderAPI v4.1 works, so there might be something wrong with PlaceholderAPI v4.2. Please reopen this issue if you find some new evidence that VirtualChest caused the problem.
Besides, I found a new problem in PlaceholderAPI that it cannot parse `%economy_balformat%` correctly while v3.x does.

**Comment by Wundero** [comment]
@ustc-zzzz Is it possible to show me what your testing environment was? Using 4.2 I was unable to replicate the issues when I had an economy plugin installed, and when I didn't I wouldn't expect economy placeholders to work in the first place. If you use `/papi p <player> <placeholder>`, you can see what the plugin is returning and hover over placeholder strings if something doesn't work to see additional information.

**Comment by ustc-zzzz** [comment]
@KhaozFrost @Wundero I've updated everything and this bug magically disappeared. I'm now using:
* SpongeVanilla 1.10.2-5.2.0-BETA-398
* TotalEconomy 1.7.1
* PlaceholderAPI 4.2

Maybe an operation I did could help you: I just delete everything in `config/totaleconomy`. Maybe you can backup your economy plugin configuration folder, delete and regenerate it, then try again if this bug is avaliable.

**Comment by KhaozFrost** [comment]
I'm using 
EconomyLite-5.0.0-2.12.0.jar
(doesn't seem to be a converter available so it really isn't viable to switch)
PlaceholderAPI-4.2.jar
VirtualChest v0.4.3 (4.2 with 4.3 broken)
I'm also having issues with
the example config where handhelditem costs arent responding as requirements.

**Comment by KhaozFrost** [comment]
also tested
TotalEconomy-1.7.0-LEGACY.jar
PlaceholderAPI-4.2.jar
VirtualChest v0.4.3

still doesn't work. I believe the biggest issue is that these tests of mine are on 1.10.2 API (modded server)
And you're testing these on 1.11.2/12 (API 6/7)

even the example cofigs that cost do not work correctly.
