### ISSUE TITLE
Insanely high timings...

### ISSUE THREAD

**Issue by KhaozFrost** [ustc-zzzz/VirtualChest#37]
https://timings.aikar.co/?id=708c697ffa814539b9233182dbfe8c7b
https://timings.aikar.co/?id=cde0447402d34237b28dfc4872ce6b66

and i don't know why. this is ruining the experience of my server but i need the guis.

**Comment by ustc-zzzz** [comment]
Well, the timings does not contain enough information, and I've tried some ways to reproduce the performance issue, but I failed.

Maybe your answers to some questions could help me:
* How many chest GUIs have you created? What's the frequency for players to open the GUIs respectively?
* What's the `UpdateIntervalTick` which you set for GUIs?
* Under what circumstance is this problem most likely to happen? For example, after 100 players joined in and logged out? Or it happens a few hours after you start your server? Or it happens just as soon as you start it?

Besides, if possible, please use JVisualVM (which has been already included in Oracle JDK) and create a CPU sampling snapshot then find the hot spots. JVisualVM provides much more information than timings.

**Comment by KhaozFrost** [comment]
UpdateIntervalTick is 60
Chest guis maybe 50 so far
After a few hours with just 1 person on the server

I switched back to 3.9 using the exact same menus I've already created and I havent had any timing issues what-so-ever but in doing so I lost several of my menus due to the config breaking changes and you dont seem to have a converter to switch between the two sadly. 
The most noticeable thing i can think of that 3.9 doesnt offer is the whole updateintervaltick thing so I'm not sure what i could set that to in order to have it nearly the same as 3.9

**Comment by ustc-zzzz** [comment]
I had made a profile by myself and found some performance bottlenecks, then I fixed it in v0.4.7. I don't know if v0.4.7 could solve the problem in this issue.

**Comment by PixelmonPRO** [comment]
@KhaozFrost Try to remove any animations (on tics) and remove the parameter `UpdateIntervalTick` in configs. It helped me to reduce the lags to a minimum :)

**Comment by ustc-zzzz** [comment]
VC has added more information to timings report. Please check the timings report and find where the performance bottlenecks occur.

**Comment by PixelmonPRO** [comment]
At high online, with the latest version `Pixelmon Mod 6.2.3`, i have issue very high timings... 
_Maximum online_: https://timings.aikar.co/?id=683e815250c34d47afea95ba01a0e9af / https://timings.aikar.co/?id=bd9989310a7d426d9f8e2cc73cd59656
_Medium online_: https://timings.aikar.co/?id=179368d1ffad48b9acd6a797b7ab8017
_Remove all conf_: https://timings.aikar.co/?id=41fda4162b62498387a025343bd694e6
How can I fix this?
