### ISSUE TITLE
Changes to Enchantment API causing breakages

### ISSUE THREAD

**Issue by merjilin** [ustc-zzzz/VirtualChest#38]
Hey there! There have been changes to the enchantment API in API 7 that seemed to go under the radar. Unfortunately, this has meant virtual chests now errors on startup upon loading the configuration. 

Here is the pull request for the enchantment API changes https://github.com/SpongePowered/SpongeAPI/pull/1687

And here is the fml-server-latest.log https://gist.github.com/merjilin/cde592a71b386f80f407617de1d658e4

The error in question is this: https://gist.github.com/merjilin/e3e8f07f82b270dc250a0eb46f557038

Environment:
- spongeforge-1.12.2-2555-7.0.0-BETA-2758.jar 
- VirtualChest-0.4.3.jar 

Hopefully this won't be much of a hassle :)

Kind regards, merjilin

**Comment by ustc-zzzz** [comment]
Please test if [VirtualChest v0.4.4](https://github.com/ustc-zzzz/VirtualChest/releases/tag/v0.4.4) has fixed this issue.

**Comment by Krosta8** [comment]
I wanted to test it, but PlaceHolderAPI is not working too, so I can't say, that it is working, but the server start without any problem with VirtualChest (no error), just errors from PlaceHolderAPI now.

**Comment by merjilin** [comment]
The plugin is now launching with no error, but nothing is being displayed in the menu despite the conf file being correct. Could this be due to PlaceholderAPI not being updated yet?

**Comment by merjilin** [comment]
Fixed the PlaceholderAPI issue and everything seems to be working. Thanks for the quick fix! :)
