### ISSUE TITLE
No Config Files

### ISSUE THREAD

**Issue by zachdoug24** [ustc-zzzz/VirtualChest#39]
I've run my server and am using API 5.0, used API 6.0 and even API 7.0, yet nothing is created.

![image](https://user-images.githubusercontent.com/30303429/34313969-fe543c02-e734-11e7-9686-e1536046d948.png)

**Comment by ustc-zzzz** [comment]
Is there any errors printed in the log files?

**Comment by ustc-zzzz** [comment]
I decided to close this issue since there are not any response for more than two weeks.
