### ISSUE TITLE
Error on open/close event

### ISSUE THREAD

**Issue by Krosta8** [ustc-zzzz/VirtualChest#43]
Hello,
I updated to version 0.4.5 and I'm not able to open correctly virtualchest's menu. It is always empty (tried example and example2 too).
On Sponge API 5.2.0 is it OK, but on Sponge API 7.1.0 just empty menu.
Here is error on open: https://pastebin.com/KNrHNP2X
Here is error on close: https://pastebin.com/h8JrnvQN

SpongeForge version 1.12.2 7.1.0 Build 2821
VirtualChest version 0.4.5

**Comment by ustc-zzzz** [comment]
Well, the reason is that api 7 has changed the way to set/clear permissions. Fixed in [v0.4.6](https://github.com/ustc-zzzz/VirtualChest/releases/tag/v0.4.6)
