### ISSUE TITLE
Contents of menus empty

### ISSUE THREAD

**Issue by Jaskirat-Boparai** [ustc-zzzz/VirtualChest#44]
Virtualchest version: 0.4.6
Spongeforge version: spongeforge-1.12.2-2555-7.1.0-BETA-2817.jar

The Issue: When opening any menus, the contents are empty. 
No error is given in console, the menus are simply empty on the inside. 
Here is a copy of one of the configurations for one of my menus (note, even the example and example2 menus are empty): https://pastebin.com/4YTWhG4n

I saw this issue was supposed to be fixed in v0.4.6 but seems not.

**Comment by Jaskirat-Boparai** [comment]
Updated to spongeforge-1.12.2-2555-7.1.0-BETA-2825.jar, issue still present.
Also worth mentioning this is on a server hosting the FTB: Revelation modpack.

**Comment by Krosta8** [comment]
You have version of VirtualChest 0.4.6 but menu is made for version 0.3.x.
You have to change your config to 0.4.x version or downgrade to 0.3.x version

**Comment by Jaskirat-Boparai** [comment]
Ah right, thanks! Yep, changing config worked out fine, my bad.
