### ISSUE TITLE
command cost don't work

### ISSUE THREAD

**Issue by THEJean-Kevin** [ustc-zzzz/VirtualChest#47]
Hello,

I try to use cost prefix but when the command is execute I have this error : 
https://pastebin.com/AG5GCvYN

> SecondaryAction {
      Command = "cost:9900; kit shop-applied"
      KeepInventoryOpen = false
}
Requirements = "%economy_balance% >= 9900"
> 

And when I specify the currency I have another error : 
https://pastebin.com/6JCX4k1p

> SecondaryAction {
			Command = "cost: aurions:9900; kit shop-applied"
			KeepInventoryOpen = false
		}
		Requirements = "%economy_balance% >= 9900"

> 

VirtualChest-0.4.7.jar
spongeforge-1.12.2-2586-7.1.0-BETA-2881.jar

**Comment by ustc-zzzz** [comment]
VC distinguishes different currencies by their ids, so it should be `totaleconomy:aurions` if you're using TotalEconomy, and it should be `economylite:aurions` if you're using EconomyLite.
