### ISSUE TITLE
HandheldItem Requirement 

### ISSUE THREAD

**Issue by MageFX** [ustc-zzzz/VirtualChest#48]
Using Sponge 1.12.2 2931 / VirtualChest 0.4.8

>      HandheldItem {
        ItemType = "minecraft:white_shulker_box"
        Count = 1
        UnsafeDamage = 0
        UnsafeData {
            BlockEntityTag {
                Items=[
                    {
                        Count=1
                        Damage=0
                        Slot=0
                        id="minecraft:stone"
                    },
                    {
                        Count=1
                        Damage=0
                        Slot=3
                        id="minecraft:lapis_ore"
                    }
                ]
            }
        }

Will take a empty white_shulker_box and not read the BlockEntityTag as a requirement.

**Comment by ustc-zzzz** [comment]
`HandheldItem` does not support NBT yet. Maybe I should design a way to support NBT carefully.

**Comment by randombyte-developer** [comment]
Just a simple check `ItemStack#equalTo(ItemStack)`.

**Comment by MageFX** [comment]
In relation to the issue also when `KeepInventoryOpen = false` items will not be taken. Rather dropped to the floor.

**Comment by ustc-zzzz** [comment]
Now it's supported in VC v1.0.0-alpha.
> In relation to the issue also when `KeepInventoryOpen = false` items will not be taken. Rather dropped to the floor.
It is still an issue now. Keep this issue open before the bug is fixed.

**Comment by ustc-zzzz** [comment]
The related problems seems to have been completely resolved, and please reopen the issue or create a new one if the bug occurs again.

**Comment by MageFX** [comment]
https://pastebin.com/RseHYLg9

Beta4 

Issue occurs again.  It does not read the NBT
