### ISSUE TITLE
console并不好用

### ISSUE THREAD

**Issue by a1640727878** [ustc-zzzz/VirtualChest#51]
![64ks5664h0swxutwdv3gmvo](https://user-images.githubusercontent.com/29010620/38545913-c55ba184-3cdd-11e8-97a2-71ae1d91250a.png)
按照图片上那样写,插件根本不识别

**Comment by ustc-zzzz** [comment]
你这一行里有四个引号，注意转义问题。
另外涉及到大量引号的场合我建议使用[多行字符串](https://github.com/ustc-zzzz/HOCON-CN-Translation/blob/master/HOCON.md#%E5%A4%9A%E8%A1%8C%E5%AD%97%E7%AC%A6%E4%B8%B2)
