### ISSUE TITLE
Alternative Items in Menu

### ISSUE THREAD

**Issue by MageFX** [ustc-zzzz/VirtualChest#53]
Is it possible to assign a secondary item to a slot the replaces the main item based on if a player has a specific permission?

So say slot0 is stone can i give a player perm.x and when he opens the menu again the stone would appear as say a diamond?

**Comment by ustc-zzzz** [comment]
It is possible: <https://github.com/ustc-zzzz/VirtualChest/wiki/3-Slots-And-Requirements#requirements>
The value of a slot could be a list.
