### ISSUE TITLE
Permission Requirements

### ISSUE THREAD

**Issue by MageFX** [ustc-zzzz/VirtualChest#54]
I'm currently having issues with applying multiple permissions to the Requirements. Have I formatted this incorrectly? Its still displaying the pixelmon:beacon_badge when I have all required perms. It works fine if I only require 1 permission.

>   Slot25 = [{
    Item {
      Count = 1
      ItemType = "pixelmon:dynamo_badge"
      UnsafeDamage = 0
      DisplayName = "&a&lUnlocked"
      ItemLore = [
          "&bClick for Reward"
          ]
    }
    Requirements = [
        "player.hasPermission('lock.one')"
        "player.hasPermission('lock.two')"
        "player.hasPermission('lock.three')"
        "player.hasPermission('lock.four')"
        "player.hasPermission('lock.five')"
        "player.hasPermission('lock.six')"
        ]
  },
  {
    Item {
      Count = 1
      ItemType = "pixelmon:beacon_badge"
      UnsafeDamage = 0
      DisplayName = "&c&lLocked"
      ItemLore = [
          "&aUnlock the combination"
          ]
    }
  }]

**Comment by MageFX** [comment]
Solution Found

**Comment by ustc-zzzz** [comment]
The value of `Requirements` is JavaScript.

You can just use `&&` to concat the requirements like this:
```javascript
player.hasPermission('a.b.c') && player.hasPermission('d.e.f') && player.hasPermission('g.h.i')
```

If you want the code looks better, you can set the value like this:
```javascript
['a.b.c', 'd.e.f', 'g.h.i'].every(function(permission){return player.hasPermission(permission);})
```

**Comment by MageFX** [comment]
Resolved Thank You
