### ISSUE TITLE
Using Custom Heads

### ISSUE THREAD

**Issue by MageFX** [ustc-zzzz/VirtualChest#59]
As a example I would like to use this Head in a GUI. However I can not work out how I would format the config to display this head using the texture.

https://www.minecraft-heads.com/custom/heads/decoration/6343-paint-bucket-white

If you could provide a example that would be fantastic.

**Comment by MageFX** [comment]
Or possibly supporting this plugin so I could use "byte-items:<itemname>"
https://ore.spongepowered.org/RandomByte/ByteItems

**Comment by randombyte-developer** [comment]
If there are any questions, I'm here. (Or on discord)

**Comment by ustc-zzzz** [comment]
Just use `UnsafeData` like this:
```javascript
Item {
  Count = 1
  UnsafeDamage = 3
  ItemType = "minecraft:skull"
  DisplayName = "Paint Bucket (white)"
  UnsafeData {
    SkullOwner {
      Id = "cb2f0497-e676-4f5b-ae80-049f987c9481"
      Properties {
        textures = [{
          Value = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTg2Y2Q1MjljOWRjNTQ4ODRmNTRmMzdhZWNhMzBmNThhYTk5M2U2YjM1OTFkYTA1MmQ4Nzc1ZjFjNzkzOTAifX19"
        }]
      }
    }
  }
}
```

**Comment by randombyte-developer** [comment]
The `UnsafeData` can be copied from a serialized byte-item.
