### ISSUE TITLE
Command Aliases Overwrite Nucleus

### ISSUE THREAD

**Issue by GershonR** [ustc-zzzz/VirtualChest#6]
Using version VirtualChest-0.3.0
I created the alias:

```
    command-aliases {
        m-e=example
        m-e2=example2
        menu-example=example
        menu-example2=example2
        kits=kits
        menukit=kits
    }

```

/menukit works fine, but the command /kits does not override the Nucleus /kits command, is it possible to do that?

**Comment by ustc-zzzz** [comment]
I am not sure if you had noticed the warning message when you started the server as follows:
![screenshot from 2017-03-30 14-39-24](https://cloud.githubusercontent.com/assets/8004211/24491059/08a3d80c-1558-11e7-90be-bd3f607987ac.png)

As is described above, open the `config/sponge/global.conf` file and modify the part of the configuration file:
```
commands {
    aliases {
        kits=virtualchest
    }
}
```
It will tell sponge that the command provided by virtualchest should be the default command.

**Comment by GershonR** [comment]
Alright thanks you so much!
