### ISSUE TITLE
[Request] Negative Value Display Amounts

### ISSUE THREAD

**Issue by KhaozFrost** [ustc-zzzz/VirtualChest#60]
I don't know if its possible in sponge but back in Spigot you could change the Value to a negative number to display a negative quantity for like Buy/Sell shops 
http://prntscr.com/jwmhzo

would also be nice to be able to display values above 64 aswell.

**Comment by ustc-zzzz** [comment]
[The implementation of SpongeAPI](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/item/inventory/SpongeItemStackBuilder.java#L100) does not seem to support abnormal count of an `ItemStack`. There may be some "weird" ways to implement it but it is likely to be unstable and produce some unexpected bugs. If you think that this feature is really important while SpongeAPI haven't implement it yet, you can submit an issue to the official repository of SpongePowered.
