### ISSUE TITLE
Help with Tellraw

### ISSUE THREAD

**Issue by RJHaytree** [ustc-zzzz/VirtualChest#62]
Hey there, ustc-zzzz!

I've encountered an issue which I have been unable to resolve myself, so I was hoping I could get some input whenever possible.

I am trying to setup VC to run a tellraw command when prompted, however the quotation marks used to contain a command, and the quotation marks used in the JSON message are conflicting.

Here is the tellraw command I am attempting to setup `"tellraw: ["",{"text":"T","color":"gold","bold":true},{"text":"T","color":"red","bold":true},{"text":" >> ","color":"dark_gray","bold":false},{"text":"Click me to make a suggestion!","color":"gray","clickEvent":{"action":"open_url","value":"https://forum.toastynetworks.net/forums/ideas-and-feedback.10/"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Make a suggestion here!","color":"gold"}]}}}]"`

and here is the error in console when reloading. https://gist.github.com/RJHaytree/58e30096cb3dd80171c433a72a858f55

Hopefully this is solvable with a bit of guidance :)

**Comment by ustc-zzzz** [comment]
You should escape double quotes in your quoted string (like `"tellraw: {\"text\": \"xxxxxx\"}"`), or you can use  raw strings (like `"""tellraw: {"text": "xxxxxx"}"""`) to avoid escaping.

**Comment by RJHaytree** [comment]
Aha! Thank you. I've finally got it working :)
