### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by LXSN** [ustc-zzzz/VirtualChest#63]
hey guys
   do you konw  when you open the vc  your mouse hovers over something and then press q, it will fall off and can be picked up.
  At present, my server is investigating this problem. I don't know whether it is caused by plug-ins or modules, but please pay attention to it.

**Comment by ustc-zzzz** [comment]
Please make sure you are using the latest version of VC (1.0.0-beta-6), and please tell me your Minecraft Version, Forge Version, and SpongeForge Version.
