### ISSUE TITLE
How would i apply unbreakable nbt inside the menu?

### ISSUE THREAD

**Issue by KhaozFrost** [ustc-zzzz/VirtualChest#66]
need this for showing custom textures so im wondering how its possible; if its possible.

**Comment by ustc-zzzz** [comment]
You can use the `Unbreakable` and `HideUnbreakable` options like this:
```javascript
Item {
    Count = 1
    ItemType = "minecraft:wheat"
    UnsafeDamage = 0
    Unbreakable = true
    HideUnbreakable = true
}
```
Both of the two options are available in the latest version (`1.0.0-beta-6`).
