### ISSUE TITLE
Virtualchest crash my server sometimes

### ISSUE THREAD

**Issue by xion87** [ustc-zzzz/VirtualChest#70]
I got a big crash today:
Using
Spongeforge 1.12.2-2705-7.1.0-BETA-3361 (forge 2705)
Pixelmon Reforged Version 1.12.2-6.3.4 
I use also GTS (Global Trade Station) for pixelmon that open a gui (is a relevant mod since spongeforge staff told me that is involved too)

My config, just have 1 item and one chest on "menu" folder called by the command /aiuto https://gist.github.com/xion87/bc1073bf6496a1abbd738bf2dcba7a8b

The log was like 2 gb and i can't open it, instead on latest rows of debug.log i see this https://gist.github.com/xion87/dde2da6052730a0c571561b9c30c6f11

**Comment by ustc-zzzz** [comment]
Update your VirtualChest version from `v1.0.0-alpha` to `v1.0.0-rc.1` first.

**Comment by xion87** [comment]
i already updated and there was another crash with your latest version that i don't loged

**Comment by ustc-zzzz** [comment]
Closed since it has not been reproduced by anyone else for a long time.
