### ISSUE TITLE
Item requirement

### ISSUE THREAD

**Issue by galoti** [ustc-zzzz/VirtualChest#71]
**Hello!! In this example is possible change the economy requirement to some item requirement ?**
```javascript
Slot0 {
    Item {
        Count = 1
        ItemType = "minecraft:wheat"
        UnsafeDamage = 0
        DisplayName = "&lWheat seller"
        ItemLore = [
            "&ePrice for %player_name%: $10 => 9 wheats"
            "&eYou can left or right click to buy some wheats"
        ]
    }
    PrimaryAction {
        Command = "cost: 10; console: give %player_name% minecraft:wheat 9"
        KeepInventoryOpen = true
    }
    SecondaryAction {
        Command = "cost: 10; console: give %player_name% minecraft:wheat 9"
        KeepInventoryOpen = true
    }
    Requirements = "%economy_balance% >= 10"
}
```
   **I want to change the wheat cost to 2 iron bars and 2 gold bars with specific nbtData (Name and lore). If its possible, could you show an example ?**

**Comment by ustc-zzzz** [comment]
It is possible. Please refer to the [`PrimaryAction` and `SecondaryAction`](https://github.com/ustc-zzzz/VirtualChest/wiki/3-Slots-And-Requirements#primaryaction-and-secondaryaction) part in the wiki, and  pay extra attention to the parts related to `HandheldItem`.

**Comment by galoti** [comment]
**Hello!! So, after some reading I was capable to make what I wanted. But I still don't know how I deduct 3 of each item. My intention is run the command only if the player as 3 ${aliases.ncxdragon} and 3 ${aliases.ncxflying} on inventory.**

```javascript   
   Slot15 = ${aliases.uncxdrafly} {
    PrimaryAction = [{
      Command = "cost-item: 3; console: crates give case uncxdrafly %player_name% 1"
	  HandheldItem = ${aliases.ncxdragon}
      KeepInventoryOpen = true
    }, {
	  Command = "cost-item: 3; console: crates give case uncxdrafly %player_name% 1"
	  HandheldItem = ${aliases.ncxflying}
      KeepInventoryOpen = true
    }]
    SecondaryAction = [{
      Command = "cost-item: 3; console: crates give case uncxdrafly %player_name% 1"
	  HandheldItem = ${aliases.ncxdragon}
      KeepInventoryOpen = true
    }, {
	  Command = "cost-item: 3; console: crates give case uncxdrafly %player_name% 1"
	  HandheldItem = ${aliases.ncxflying}
      KeepInventoryOpen = true
    }]
  }
```

**Comment by ustc-zzzz** [comment]
Well, the current design of VirtualChest does not support the simultaneous deduction of two types of items, because a player can only hold an item stack of one type (under the mouse pointer) to submit an action.

**Comment by galoti** [comment]
Oh... ok :/

**Comment by hellbringer616** [comment]
if using SearchInventory = true would that remove the requirement of being handheld?

**Comment by hellbringer616** [comment]
Doesn't seem to function unfortunately.. seems even with `SearchInventory` it can only grab one item

**Comment by ustc-zzzz** [comment]
Close this issue because it seems that @hellbringer616 has submitted a new issue (#74) for this.
