### ISSUE TITLE
HandheldItem and heads with texture

### ISSUE THREAD

**Issue by galoti** [ustc-zzzz/VirtualChest#73]
Hello, I'm using the plugin to trade heads with texture for another item. Some of them use the same texture with different lore and name, but the plugin confuses heads with the same texture.

**Comment by ustc-zzzz** [comment]
Sorry, I don't fully understand what you mean...Could you provide an example (such as the NBT of items and the `HandheldItem` option) about what is "confused" by the plugin?

**Comment by ustc-zzzz** [comment]
Well...I understand what you mean. Only `UnsafeData` is supported for identifying NBTs of an item as `HandheldItem`. If you want to identify items whose lore contains a line of specific text string, you may need to add a field named `UnsafeData.display.Lore` (`UnsafeData.display.Name` for `DisplayName`) like this:
```javascript
UnsafeData {
  display {
    Lore = [
      "the lore you want for identification"
    ]
  }
  SkullOwner {
    Id = "6616a590-e326-442d-8806-b313fca1b5d5",
    Properties {...}
  }
}
```
