### ISSUE TITLE
The problem of enchantment

### ISSUE THREAD

**Issue by situfangjian** [ustc-zzzz/VirtualChest#77]
Hello, I am a Chinese player. I like this plug-in very much. It's too powerful. But I have a problem. The module I use is Pixelmon reforged, and I want to use pixelmon_sprite for Enchantments. But I don't know how to determine whether pixelmon_sprite is Enchantments by code. I hope you see it and can help me answer it. Thank you.

**Comment by SeraphJACK** [comment]
请直接说中文
