### ISSUE TITLE
[REQUEST] Add Itemizer support

### ISSUE THREAD

**Issue by hellbringer616** [ustc-zzzz/VirtualChest#80]
Hello,
would it be possible to add support to reference Itemizer items for items?
https://github.com/OnapleRPG/Itemizer

I'd like to make a series of custom items that monsters drop and use them as costs to run various commands using your plugin.

**Comment by hellbringer616** [comment]
Adding Byte-Item support would make this request less valid as you can register the Itemizer item within Byte-Items.

still would like Itemizer support though :)

**Comment by ustc-zzzz** [comment]
ByteItem support was added in acb8220.
