### ISSUE TITLE
Problem with Papi and custom parameters.

### ISSUE THREAD

**Issue by drassasmc** [ustc-zzzz/VirtualChest#84]
When I create a menu with an item if I put a papi with custom parameter it is not shown.
Ex.:
Plugins: Sponge(vanilla/forge),Nucleus, Papi, VirtualChest

Server:
"/nick &aNew&1name" (My nick it's now Newname in light green & dark blue)

VirtualChest config:

> 
> virtualchest {
>   TextTitle = "&3&lProfile"
>   Rows = 3
>   UpdateIntervalTick = 20
>   AcceptableActionIntervalTick = 20
>   Slot10 {
>     Item {
>       ItemType = "minecraft:skull"
>       Count = 1
>       UnsafeDamage = 3
>       RepresentedPlayer = {
>         UUID = "%player_uuid%"
>       }
>       DisplayName = "&3%player_name%"
>       ItemLore = [
>         ""
>         "&7Nick: %nucleus_displayname%"
>       ]
>     }
>   }

When I use that menu I see Newname without color in the item lore.
I tested it with the name of the item too.

Can you fix it? 
Thanks & Regards!

**Comment by ustc-zzzz** [comment]
Fixed in v1.0.0-rc-2
