### ISSUE TITLE
 Is there anything wrong with this code?  I can not get the player to buy 64 by 128,000

### ISSUE THREAD

**Issue by ClarkHalf** [ustc-zzzz/VirtualChest#85]
Slot12 = [
    ${aliases.pokeball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """givemoney %player% -2000;
                     console: give %player_name% pixelmon:poke_ball 1"""
        KeepInventoryOpen = true
	  }  
    }
    ${aliases.pokeball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryShiftAction = {
        Command = """givemoney %player% -128000;
                     console: give %player_name% pixelmon:poke_ball 64;"""
        KeepInventoryOpen = true
      }
	}
    ${aliases.pokeball}
  ]

**Comment by ClarkHalf** [comment]
@ustc-zzzz

**Comment by ustc-zzzz** [comment]
Exchange the order of the one including `%economy_balance% >= 2000` and the one including `%economy_balance% >= 128000`. The latter is a sufficient condition for the former.
