### ISSUE TITLE
 Buy items very fast do not give all

### ISSUE THREAD

**Issue by ClarkHalf** [ustc-zzzz/VirtualChest#86]
When I buy items very fast with virtualchest, it ends up not givin 'all the items at the end.

**Comment by ClarkHalf** [comment]
@ustc-zzzz

**Comment by ustc-zzzz** [comment]
Could you provide an example and a list of mods/plugins on your server here?

**Comment by ClarkHalf** [comment]
http://prntscr.com/mus05n

aliases {
  pokeball {
    Item {
      Count = 1
      ItemType = "pixelmon:poke_ball"
      UnsafeDamage = 0
      DisplayName = "&cPoke&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:poke_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:poke_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  greatball {
    Item {
      Count = 1
      ItemType = "pixelmon:great_ball"
      UnsafeDamage = 0
      DisplayName = "&9Great&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
      ItemType = "pixelmon:great_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
      ItemType = "pixelmon:great_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  ultraball {
    Item {
      Count = 1
      ItemType = "pixelmon:ultra_ball"
      UnsafeDamage = 0
      DisplayName = "&eUltra&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
      ItemType = "pixelmon:ultra_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
      ItemType = "pixelmon:ultra_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  levelball {
    Item {
      Count = 1
      ItemType = "pixelmon:level_ball"
      UnsafeDamage = 0
      DisplayName = "&7Level&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:level_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:level_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  moonball {
    Item {
      Count = 1
      ItemType = "pixelmon:moon_ball"
      UnsafeDamage = 0
      DisplayName = "&8Moon&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:moon_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:moon_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  friendball {
    Item {
      Count = 1
      ItemType = "pixelmon:friend_ball"
      UnsafeDamage = 0
      DisplayName = "&aFriend&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:friend_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:friend_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  loveball {
    Item {
      Count = 1
      ItemType = "pixelmon:love_ball"
      UnsafeDamage = 0
      DisplayName = "&dLove&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:love_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:love_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  heavyball {
    Item {
      Count = 1
      ItemType = "pixelmon:heavy_ball"
      UnsafeDamage = 0
      DisplayName = "&1Heavy&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:heavy_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:heavy_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  fastball {
    Item {
      Count = 1
      ItemType = "pixelmon:fast_ball"
      UnsafeDamage = 0
      DisplayName = "&6Fast&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:fast_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:fast_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  repeatball {
    Item {
      Count = 1
      ItemType = "pixelmon:repeat_ball"
      UnsafeDamage = 0
      DisplayName = "&eRepeat&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:repeat_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:repeat_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  timerball {
    Item {
      Count = 1
      ItemType = "pixelmon:timer_ball"
      UnsafeDamage = 0
      DisplayName = "&fTimer&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:timer_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:timer_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  diveball {
    Item {
      Count = 1
      ItemType = "pixelmon:dive_ball"
      UnsafeDamage = 0
      DisplayName = "&1Dive&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:dive_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:dive_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  luxuryball {
    Item {
      Count = 1
      ItemType = "pixelmon:luxury_ball"
      UnsafeDamage = 0
      DisplayName = "&8Luxury&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:luxury_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:luxury_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  healball {
    Item {
      Count = 1
      ItemType = "pixelmon:heal_ball"
      UnsafeDamage = 0
      DisplayName = "&dHeal&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:heal_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:heal_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  duskball {
    Item {
      Count = 1
      ItemType = "pixelmon:dusk_ball"
      UnsafeDamage = 0
      DisplayName = "&2Dusk&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:dusk_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:dusk_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  premierball {
    Item {
      Count = 1
      ItemType = "pixelmon:premier_ball"
      UnsafeDamage = 0
      DisplayName = "&fPremier&7Ball"
      ItemLore = [
        "  &3Comprar por &a2000 Moedas &7» &c1 &funidade "
		" "
        "  &3Vender por &c50 Moedas &7» &c1 &funidade "
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:premier_ball"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 64; cost: -50"
      HandheldItem {
        ItemType = "pixelmon:premier_ball"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 2304
    }
    KeepInventoryOpen = true
    }
  }
  black-pane-item {
    Item {
      Count = 1
      ItemType = "minecraft:stained_glass_pane"
      UnsafeDamage = 10
      DisplayName = ""
    }
    Requirements = ""
  }
  purple-pane-item {
    Item {
      Count = 1
      ItemType = "minecraft:stained_glass_pane"
      UnsafeDamage = 15
      DisplayName = ""
    }
    Requirements = ""
 }
  white-pane-item {
    Item {
      Count = 1
      ItemType = "minecraft:stained_glass_pane"
      UnsafeDamage = 15
      DisplayName = ""
    }
    Requirements = ""
 }
  ajuda2 {
    Item {
      Count = 1
      ItemType = "minecraft:paper"
      UnsafeDamage = 0
      DisplayName = "&3&lComo &c&lVENDER"
      ItemLore = [
        "  &3Para vender 1 un basta clicar com o &cBotão Direito &3"
        "  &3Para vender 64 un basta clicar com o &cShift +Botão Direito &3"
      ]
    }
    Requirements = ""
 }
  ajuda1 {
    Item {
      Count = 1
      ItemType = "minecraft:paper"
      UnsafeDamage = 0
      DisplayName = "&3&lComo &a&lCOMPRAR"
      ItemLore = [
        "  &3Para comprar bastar clicar com o &aBotão Esquerdo"
        "  &3Para comprar 64 un bastar clicar com o &aShift + Botão Esquerdo"
      ]
    }
    Requirements = ""
 }
  ajuda3 {
    Item {
      Count = 1
      ItemType = "minecraft:paper"
      UnsafeDamage = 0
      DisplayName = "&3&lComo &a&lCOMPRAR &764 &a&lUnidades"
      ItemLore = [
        "  &3Para comprar 64 un bastar clicar com o &aShift + Botão Esquerdo"
		"  &cPara comprar 64 un, É preciso ter o valor minimo x64"
		"  &3Exemplo : &72000 &fx &c64 &f= &a12800"
		"  &3Você precisa ter &a12800 para comprar &c64 &3unidades"
      ]
    }
    Requirements = ""
 }
  saldo {
    Item {
      Count = 1
      ItemType = "pixelmon:marsh_badge"
      UnsafeDamage = 0
      DisplayName = "&3&lSeu saldo"
      ItemLore = [
        "&eMoedas &8» &7$%economy_balance_moeda%"
      ]
    }
    Requirements = ""
 }
}
virtualchest {
    TextTitle = "&c&lPoke&f&lbolas"
    Rows = 5
    UpdateIntervalTick = 10	
    Slot0 = [
        ${aliases.black-pane-item}
        ]
	Slot1 = [
        ${aliases.black-pane-item}
        ]
	Slot2 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot3 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot4 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot5 = [
        ${aliases.saldo}
        ]
	Slot6 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot7 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot8 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot9 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot11 = [
        ${aliases.white-pane-item}
        ]
    Slot12 = [
    ${aliases.pokeball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """console: meco remove %player_name% Moeda 2000;
                     console: bi give %player_name pixelmon:poke_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:poke_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.pokeball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:poke_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.pokeball}
  ]
	Slot13 = [
    ${aliases.greatball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:great_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:great_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.greatball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:great_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.greatball}
  ]
	Slot14 = [
    ${aliases.ultraball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:ultra_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:ultra_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.ultraball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:ultra_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.ultraball}
  ]
	Slot15 = [
    ${aliases.levelball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:level_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:level_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.levelball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:level_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.levelball}
  ]
	Slot16 = [
    ${aliases.moonball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:moon_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:moon_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.moonball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:moon_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.moonball}
  ]
	Slot10 = [
        ${aliases.ajuda3}
        ]
	Slot19 = [
        ${aliases.ajuda1}
        ]
	Slot28 = [
        ${aliases.ajuda2}
        ]
	Slot20 = [
        ${aliases.white-pane-item}
        ]
	Slot29 = [
        ${aliases.white-pane-item}
        ]
	Slot21 = [
    ${aliases.friendball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:friend_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:friend_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.friendball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:friend_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.friendball}
  ]
	Slot22 = [
    ${aliases.loveball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:love_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:love_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.loveball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:love_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.loveball}
  ]
	Slot23 = [
    ${aliases.heavyball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:heavy_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:heavy_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.heavyball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:heavy_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.heavyball}
  ]
	Slot24 = [
    ${aliases.fastball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:fast_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:fast_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.fastball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:fast_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.fastball}
  ]
	Slot25= [
    ${aliases.repeatball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:repeat_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:repeat_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.repeatball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:repeat_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.repeatball}
  ]
	Slot30= [
    ${aliases.timerball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:timer_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:timer_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.timerball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:timer_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.timerball}
  ]
	Slot31= [
    ${aliases.diveball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:dive_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:dive_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.diveball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:dive_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.diveball}
  ]
	Slot31= [
    ${aliases.luxuryball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:luxury_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:luxury_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.luxuryball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:luxury_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.luxuryball}
  ]
	Slot32= [
    ${aliases.healball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:heal_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:heal_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.healball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:heal_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.healball}
  ]
	Slot33= [
    ${aliases.duskball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:dusk_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:dusk_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.duskball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:dusk_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.duskball}
  ]
	Slot34= [
    ${aliases.premierball} {
      Requirements = "%economy_balance% >= 128000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:premier_ball 1"""
        KeepInventoryOpen = true
      }
      PrimaryShiftAction = {
        Command = """cost: 128000;
                     console: give %player_name% pixelmon:premier_ball 64"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.premierball} {
      Requirements = "%economy_balance% >= 2000"
      PrimaryAction = {
        Command = """cost: 2000;
                     console: give %player_name% pixelmon:premier_ball 1"""
        KeepInventoryOpen = true
      }
    }
    ${aliases.premierball}
  ]
	Slot17 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot18 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot26 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot27 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot35 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot36 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot37 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot38 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot39 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot40 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot41 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
    Slot40 {
    Item {
      ItemType = "minecraft:skull"
      Count = 1
      UnsafeDamage = 3
      RepresentedPlayer = {
          UUID = "a68f0b64-8d14-4000-a95f-4b9ba14f8df9"
          Name = "MHF_ArrowLeft"
      }
      DisplayName = "&a&lMenu das Lojas"
      ItemLore = [
        "&7Voltar para o menu das lojas"
      ]
    }
    PrimaryAction {
        Command = "vc open pixelmonitems"
        }
        IgnoredPermissions = [
            "virtualchest.open.self.loja"
      ]
  }
    Slot42 {
    Item {
      ItemType = "minecraft:skull"
      Count = 1
      UnsafeDamage = 3
      RepresentedPlayer = {
          UUID = "50c8510b-5ea0-4d60-be9a-7d542d6cd156"
          Name = "MHF_ArrowRight"
      }
      DisplayName = "&a&lProxima pagina"
      ItemLore = [
        "&7Ir para proxima pagina"
      ]
    }
    PrimaryAction {
        Command = "vc open pokebolas2"
        }
        IgnoredPermissions = [
            "virtualchest.open.self.loja"
      ]
  }
	Slot43 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot44 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
    TriggerItem {
        ItemType = ""
        EnablePrimaryAction = false
        EnableSecondaryAction = false
    }
}
