### ISSUE TITLE
Virtual Chests Stopped Working Properly - People Can Take Out Items

### ISSUE THREAD

**Issue by Skquad** [ustc-zzzz/VirtualChest#9]
I used VC to set up my item shops hooked up with the buy command. All of a sudden, this has stopped working, and players can remove the items from the virtual chests. When they go back into them they'll still be there too.

This is gamebreaking, and I have no idea what may be the cause of this.

**Comment by ustc-zzzz** [comment]
I'm not sure whether you have updated the version to 0.3.1, the newest version, which fixed a bug on higher versions of the sponge server.

**Comment by Skquad** [comment]
Sorry about this. It appears this update came out moments after we downloaded the previous one and completely overlooked it. I have updated the plugin and this is fixed.
