### ISSUE TITLE
Requirements based on LuckPerms

### ISSUE THREAD

**Issue by ClarkHalf** [ustc-zzzz/VirtualChest#90]
Requirements = "%luckperms_in_group_fundador%"

Is there a way to put the requirements into a bunch of the LuckPerms?
Like this ↑

**Comment by PixelmonPRO** [comment]
> ```
> Requirements = "%luckperms_in_group_fundador%"
> ```
> 
> Is there a way to put the requirements into a bunch of the lucky perms?
> 
> Like this /\

You can add permission to group **fundador**, example: `testnameperm.group.fundador`
And check: `Requirements = "player.hasPermission('testnameperm.group.fundador')"`
More info and examples [here](https://github.com/ustc-zzzz/VirtualChest/wiki/3-Slots-And-Requirements#frequently-used-requirement-string-patterns).

**Comment by ustc-zzzz** [comment]
It seems that it is not VirtualChest's issue because it seems that the placeholders are not implemented in the Sponge version of LuckPerms.
