### ISSUE TITLE
Requirement + second Item fails

### ISSUE THREAD

**Issue by Feutor** [ustc-zzzz/VirtualChest#93]
I followed the example at https://github.com/ustc-zzzz/VirtualChest/wiki/3-Slots-And-Requirements but this wont work, I really want the item to still appear when people cannot afford it.

Slot9 [{
	Item {
	  Count = 1
	  ItemType = "pixelmon:poke_ball"
	  UnsafeDamage = 0
	  DisplayName = "&6&lChange to Pokeball"
	  ItemLore = [
	  "&r&l&eCost: 50.000$"
	  ]
	}
	Requirements = "%economy_balance% >= 50000"
	PrimaryAction {
      Command = """ console: pokeedit %player% 1 ball:poke ;console: givemoney %player% -50000"""
      KeepInventoryOpen = true
	  }
	}, {
    Item {
    Count = 1
    ItemType = "pixelmon:poke_ball"
    UnsafeDamage = 0
	DisplayName = "&c&lChange to Pokeball"
	ItemLore = [
	"&r&l&cCost: 50.000$"
	  ]
	 }
	}]

**Comment by SourPath** [comment]
supposed to be Slot9 = [{
