### ISSUE TITLE
Any errors in this configuration?

### ISSUE THREAD

**Issue by ClarkHalf** [ustc-zzzz/VirtualChest#95]
aliases {
  black-pane-item {
    Item {
      Count = 1
      ItemType = "minecraft:stained_glass_pane"
      UnsafeDamage = 5
      DisplayName = ""
    }
    Requirements = "tick % 20 <= 10"
  }
  purple-pane-item {
    Item {
      Count = 1
      ItemType = "minecraft:stained_glass_pane"
      UnsafeDamage = 4
      DisplayName = ""
    }
    Requirements = "tick % 20 <= 10"
  }
  green-pane-item {
    Item {
      Count = 1
      ItemType = "minecraft:stained_glass_pane"
      UnsafeDamage = 7
      DisplayName = ""
    }
    Requirements = "tick % 20 <= 10"
  }
  cana {
    Item {
      Count = 1
      ItemType = "minecraft:reeds"
      UnsafeDamage = 0
      DisplayName = "&aCana de aÃ§ucar"
      ItemLore = [
	    " "
        "  &eVender cana de aÃ§ucar por 12 moedas"
		"  &aBonus [VIP]" 
      ]
    }
    SecondaryAction {
      Command = "cost-item: 1; cost: -12"
      HandheldItem {
        ItemType = "minecraft:reeds"
        UnsafeDamage = 0
        Count = 1
        SearchInventory = true
	}
    KeepInventoryOpen = true
    }
    SecondaryShiftAction {
      Command = "cost-item: 1; cost: -12"
      HandheldItem {
        ItemType = "minecraft:reeds"
        Count = 1
        UnsafeDamage = 0
        SearchInventory = true
        RepetitionUpperLimit = 1151
    }
    KeepInventoryOpen = true
    }
  }
}
virtualchest {
    TextTitle = "&a&lCana de AÃ§ucar"
    Rows = 5
    UpdateIntervalTick = 1000
    Slot0 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot1 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot2 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot5 = [
        ${aliases.black-pane-item}
        ]
	Slot3 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot4 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot6 = [
        ${aliases.black-pane-item}
        ]
	Slot7 = [
        ${aliases.black-pane-item}
        ]
	Slot8 = [
        ${aliases.black-pane-item}
        ]
	Slot9 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
    Slot10 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot17 = [
        ${aliases.black-pane-item}
        ]
	Slot18 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot22 = [
        ${aliases.cana}
		]
	Slot26 = [
        ${aliases.black-pane-item}
        ]
	Slot27 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot35 = [
        ${aliases.black-pane-item}
        ]
	Slot36 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot37 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot38 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot28 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot34 = [
        ${aliases.black-pane-item}
        ]
	Slot16 = [
        ${aliases.black-pane-item}
        ]
	Slot39 = [
        ${aliases.black-pane-item}
		${aliases.purple-pane-item}
        ]
	Slot40 = [
        ${aliases.black-pane-item}
        ]
	Slot41 = [
        ${aliases.black-pane-item}
        ]
	Slot42 = [
        ${aliases.black-pane-item}
        ]
	Slot43 = [
        ${aliases.black-pane-item}
        ]
	Slot44 = [
        ${aliases.black-pane-item}
        ]
    TriggerItem {
        ItemType = ""
        EnablePrimaryAction = false
        EnableSecondaryAction = false
    }
}

I put this setting to sell 2 cane hotbar, But he sells 2 hotbat when he literally wants, and he giva money less. Example 12 x 64 = 768 x 36 [Inv full] = 27,648 and on my last sale he gave me 27,636

**Comment by leonbio** [comment]
clark half can you help me use this plugin ?

**Comment by ClarkHalf** [comment]
Of course, But i'm brazilian, Have any problem?

**Comment by ClarkHalf** [comment]
Of course, But i'm brazilian, Have any problem?

**Comment by leonbio** [comment]
no way ! :D do you have discord facebook twitter something like that so we can contact

**Comment by ClarkHalf** [comment]
Poox_#0715

**Comment by leonbio** [comment]
what is that my friend ?

**Comment by ClarkHalf** [comment]
Discord

**Comment by leonbio** [comment]
i send you a friend request accept that

**Comment by ClarkHalf** [comment]
@ustc-zzzz

**Comment by ClarkHalf** [comment]
@ustc-zzzz

**Comment by ClarkHalf** [comment]
@ustc-zzzz

**Comment by ClarkHalf** [comment]
@ustc-zzzz  Please

**Comment by ustc-zzzz** [comment]
Seems that it is not a bug for VC itself, maybe you can ask this in the Discord community: https://discordapp.com/invite/TftabgG
