### ISSUE TITLE
Using sound actions with Pixelmon

### ISSUE THREAD

**Issue by DiamondArrow** [ustc-zzzz/VirtualChest#97]
I'm trying to use `sound: pixelmon:pixelmon.mob.turtwig:1.0` but its not working

`/playsound pixelmon:pixelmon.mob.turtwig:1.0 neutral %player%` works in Minecraft so I know I didn't type it wrong.

Does the sound action only work with Minecraft vanilla sounds or am I doing something wrong?

**Comment by ustc-zzzz** [comment]
> `/playsound pixelmon:pixelmon.mob.turtwig:1.0 neutral %player%`
You mentioned a command that works fine in Minecraft so what I guess is that the name of the sound may be `pixelmon:pixelmon.mob.turtwig:1.0` so you may try `sound: pixelmon:pixelmon.mob.turtwig:1.0:1.0` in which `pixelmon:pixelmon.mob.turtwig:1.0` is the name and `1.0` as a prefix is the volume.
